# Generated by Django 5.0 on 2023-12-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_recruiter', models.BooleanField(default=False)),
                ('is_applicant', models.BooleanField(default=False)),
                ('has_resume', models.BooleanField(default=False)),
                ('has_company', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
