# Generated by Django 5.0 on 2023-12-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
