# Generated by Django 5.0 on 2023-12-29 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='loaction',
            new_name='location',
        ),
    ]
