# Generated by Django 5.0 on 2023-12-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
