# Generated by Django 5.0 on 2023-12-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='ideal_candidate',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(),
        ),
    ]
