# Generated by Django 5.0 on 2023-12-29 03:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_ideal_candidate_alter_job_requirements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='compnay',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='job',
            name='ideal_candidate',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
