# Generated by Django 5.0 on 2023-12-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_rename_compnay_job_company_alter_job_ideal_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='published',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
