# Generated by Django 5.0 on 2023-12-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_applyjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='status',
            field=models.CharField(choices=[('Declined', 'Declinned'), ('Accepted', 'Accepted'), ('Pending', 'Pending')], max_length=100),
        ),
    ]
